######################################################################
# Automatically generated by qmake
# > qmake.exe -project
######################################################################

#TEMPLATE = subdirs
#CONFIG  += ordered
#
#SUBDIRS += $$PWD/src/pch2csv.pro
#SUBDIRS += $$PWD/test/test.pro
#

TEMPLATE = app
TARGET = FastenerPattern_Qt
QT       += core gui
# QT       += concurrent

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

CONFIG += no_keyword
# CONFIG += c++11
# LANGUAGE = C++

# QT += c++11
QMAKE_CXXFLAGS += -std=c++11

lessThan(QT_VERSION, 5.0) {
    warning("prefere to build it with Qt 5.0")
}

#-------------------------------------------------
# Boost
#-------------------------------------------------
Boost_INCLUDE_DIR  = "C:/Qt/Boost/boost_1_61_0/"
Boost_LIB_DIR      = "C:/Qt/Boost/boost_1_61_0/stage/lib/"

INCLUDEPATH += $$Boost_INCLUDE_DIR
LIBS        += -L$$Boost_LIB_DIR
DEFINES     += BOOST_MATH_DISABLE_FLOAT128


#-------------------------------------------------
# VERSION
#-------------------------------------------------
APP_VERSION = 9.99.999
DEFINES += APP_VERSION=\\\"$$APP_VERSION\\\"


#-------------------------------------------------
# INCLUDE
#-------------------------------------------------
INCLUDEPATH += $$PWD/include/


#-------------------------------------------------
# SOURCES
#-------------------------------------------------
HEADERS  += \
    $$PWD/src/core/optimizer/optimisationsolver.h \
    $$PWD/src/core/solvers/isolver.h \
    $$PWD/src/core/solvers/parameters.h \
    $$PWD/src/core/solvers/rigidbodysolver.h \
    $$PWD/src/core/units/area_moment_of_inertia.h \
    $$PWD/src/core/units/unit_system.h \
    $$PWD/src/core/abstractsplicemodel.h \
    $$PWD/src/core/fastener.h \
    $$PWD/src/core/global.h \
    $$PWD/src/core/splice.h \
    $$PWD/src/core/splicecalculator.h \
    $$PWD/src/core/tensor.h \
    $$PWD/src/editor/items/appliedloaditem.h \
    $$PWD/src/editor/items/arcarrowitem.h \
    $$PWD/src/editor/items/arrowitem.h \
    $$PWD/src/editor/items/fasteneritem.h \
    $$PWD/src/editor/items/scalableimageitem.h \
    $$PWD/src/editor/items/scalablepointitem.h \
    $$PWD/src/editor/items/symbolitem.h \
    $$PWD/src/editor/items/tensoritem.h \
    $$PWD/src/editor/items/utils_scale.h \
    $$PWD/src/dialogs/propertiesdialog.h \
    $$PWD/src/editor/backgroundview.h \
    $$PWD/src/editor/backgroundwidget.h \
    $$PWD/src/editor/flexiblescrollbar.h \
    $$PWD/src/editor/splicegraphicswidget.h \
    $$PWD/src/widgets/abstractspliceview.h \
    $$PWD/src/widgets/appliedloadwidget.h \
    $$PWD/src/widgets/fastenerwidget.h \
    $$PWD/src/widgets/mainwidget.h \
    $$PWD/src/widgets/optimisationwidget.h \
    $$PWD/src/widgets/resultwidget.h \
    $$PWD/src/widgets/solverwidget.h \
    $$PWD/src/widgets/splicetoolbar.h \
    $$PWD/src/widgets/tablewidget.h \
    $$PWD/src/about.h \
    $$PWD/src/version.h \
    $$PWD/src/mainwindow.h


SOURCES += \
    $$PWD/src/core/optimizer/optimisationsolver.cpp \
    $$PWD/src/core/solvers/parameters.cpp \
    $$PWD/src/core/solvers/rigidbodysolver.cpp \
    $$PWD/src/core/abstractsplicemodel.cpp \
    $$PWD/src/core/fastener.cpp \
    $$PWD/src/core/splice.cpp \
    $$PWD/src/core/splicecalculator.cpp \
    $$PWD/src/core/tensor.cpp \
    $$PWD/src/dialogs/propertiesdialog.cpp \
    $$PWD/src/editor/items/appliedloaditem.cpp \
    $$PWD/src/editor/items/arcarrowitem.cpp \
    $$PWD/src/editor/items/arrowitem.cpp \
    $$PWD/src/editor/items/fasteneritem.cpp \
    $$PWD/src/editor/items/scalableimageitem.cpp \
    $$PWD/src/editor/items/scalablepointitem.cpp \
    $$PWD/src/editor/items/symbolitem.cpp \
    $$PWD/src/editor/items/tensoritem.cpp \
    $$PWD/src/editor/backgroundview.cpp \
    $$PWD/src/editor/backgroundwidget.cpp \
    $$PWD/src/editor/flexiblescrollbar.cpp \
    $$PWD/src/editor/splicegraphicswidget.cpp \
    $$PWD/src/widgets/abstractspliceview.cpp \
    $$PWD/src/widgets/appliedloadwidget.cpp \
    $$PWD/src/widgets/fastenerwidget.cpp \
    $$PWD/src/widgets/mainwidget.cpp \
    $$PWD/src/widgets/optimisationwidget.cpp \
    $$PWD/src/widgets/resultwidget.cpp \
    $$PWD/src/widgets/solverwidget.cpp \
    $$PWD/src/widgets/splicetoolbar.cpp \
    $$PWD/src/widgets/tablewidget.cpp \
    $$PWD/src/mainwindow.cpp \
    $$PWD/src/main.cpp


FORMS += \
    $$PWD/src/dialogs/propertiesdialog.ui \
    $$PWD/src/widgets/appliedloadwidget.ui \
    $$PWD/src/widgets/fastenerwidget.ui \
    $$PWD/src/widgets/mainwidget.ui \
    $$PWD/src/widgets/optimisationwidget.ui \
    $$PWD/src/widgets/resultwidget.ui \
    $$PWD/src/widgets/solverwidget.ui \
    $$PWD/src/widgets/tablewidget.ui \
    $$PWD/src/mainwindow.ui

OTHER_FILES += \
    $$PWD/README.md


#-------------------------------------------------
# RESOURCES
#-------------------------------------------------
RESOURCES += $$PWD/src/resources.qrc
RESOURCES += $$PWD/src/examples/examples.qrc

win32|unix {
    RC_FILE += $$PWD/src/resources_win.rc
}


#-------------------------------------------------
# OUTPUT
#-------------------------------------------------

#-------------------------------------------------
# TARGET DIRECTORY
#-------------------------------------------------
# Needs to define a subfolder, as the *.DLL
# cannot be copied in the root folder.
#DESTDIR = build
#
#build_pass:CONFIG(debug, debug|release) {
#    unix: TARGET = $$join(TARGET,,,_debug)
#    else: TARGET = $$join(TARGET,,,d)
#}
#
